# Utiliser une image de base Node.js
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /frontend

# Copier le package.json et le package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application dans le répertoire de travail
COPY . .

# Construire l'application pour le développement
# RUN npm run dev

# Exposer le port 3000
EXPOSE 5173

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev", "--", "--host"]
