services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./databases/authentication/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/authentication_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=authentication_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: host.docker.internal:24224

  authentication-service:
    image: authentication-service:latest
    build:
      context: ./authentication
      dockerfile: Dockerfile
    # Removed the ports section to prevent direct access
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/authentication_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: host.docker.internal:24224

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - authentication-service
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES[0].ID=auth-service
      - SPRING_CLOUD_GATEWAY_ROUTES[0].URI=http://authentication-service:8082
      - SPRING_CLOUD_GATEWAY_ROUTES[0].PREDICATES[0]=Path=/authenticate
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: host.docker.internal:24224

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - backend

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    environment:
      LOG_LEVEL: warn
      LOKI_URL: http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - backend

  renderer:
    image: grafana/grafana-image-renderer:latest
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - backend

  gophish:
    image: gophish/gophish
    restart: always
    volumes:
      - ./gophish/config.json:/opt/gophish-v0.6.0-linux-64bit/config.json
      - ./gophish/sqlite:/opt/gophish-v0.6.0-linux-64bit/sqlite
      - ./gophish/crt:/opt/gophish-v0.6.0-linux-64bit/crt
    ports:
      - "3333:3333"
      - "443:443"
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: host.docker.internal:24224

  # spiderfoot:
  #   image: spiderfoot:latest
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - backend
  
  spiderfoot-api:
    build:
      context: ./spiderfoot-api
      dockerfile: Dockerfile
    image: spiderfoot-api:latest
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - postgres
      # - spiderfoot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication_db
      POSTGRES_HOST: postgres
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: host.docker.internal:24224

  postgres-formation:
    image: postgres:latest
    environment:
      POSTGRES_DB: formation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
    networks:
      - backend
    volumes:
      - ./databases/formation/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/formation_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    command: [ "postgres", "-p", "5433" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=formation_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  formation-service:
    image: formation-service:latest
    build:
      context: ./formation
      dockerfile: Dockerfile
    # Removed the ports section to prevent direct access
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/formation_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: host.docker.internal:24224


networks:
  backend:
    driver: bridge