services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./databases/authentication/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/authentication_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=authentication_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
    container_name: authentication-service
    image: authentication-service:latest
    build:
      context: ./authentication
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/authentication_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_MAIL_HOST=mailserver
      - SPRING_MAIL_PORT=25
      - SPRING_MAIL_USERNAME=${AUTH_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${AUTH_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=false
      - MAIL_FROM=sender@example.com

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - authentication-service

  dozzle:
    container_name: dozzle
    image: ghcr.io/amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - DOZZLE_ADDR=:3001
        - DOZZLE_NO_ANALYTICS=true
        - DOZZLE_BASE=/monitor
        - DOZZLE_HOSTNAME=Phish&Tips
    networks:
        - backend

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: example.com
    env_file: mailserver.env
    environment:
      - PERMIT_RELOAD=1
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    ports:
      - "25:25"     # SMTP
      - "143:143"   # IMAP
      - "587:587"   # Submission
      - "993:993"   # IMAPS
    restart: unless-stopped
    networks:
      - backend

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_DEFAULT_USE_TLS=false
      - ROUNDCUBEMAIL_DEFAULT_USE_SSL=false
      - ROUNDCUBEMAIL_SMTP_USER=%u
      - ROUNDCUBEMAIL_SMTP_PASS=%p
    ports:
      - "8070:80"
    depends_on:
      - mailserver
    restart: unless-stopped
    volumes:
      - webmail_data:/var/www/html
      - ./roundcube/config/config.inc.php:/var/www/html/config/config.inc.php
    networks:
      - backend

  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    volumes:
      - gophish-data:/opt/gophish
      - ./gophish/config.json:/opt/gophish/config.json
    ports:
      - "3333:3333" # Remove in prod
      - "80:80"
    depends_on:
      - mailserver
    restart: unless-stopped
    networks:
      - backend

  postgres-formation:
    container_name: postgres-formation
    image: postgres:latest
    environment:
      POSTGRES_DB: formation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./databases/formation/pgdata:/var/lib/postgresql/data
      - ./databases/scripts/formation_init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=formation_db --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  formation-service:
    container_name: formation-service
    image: formation-service:latest
    build:
      context: ./formation
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      postgres-formation:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-formation:5432/formation_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./formation/data:/var/formation/data

#  scoring-service:
#    container_name: scoring-service
#    image: scoring-service:latest
#    build:
#      context: ./scoring
#      dockerfile: Dockerfile
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/authentication_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#    networks:
#      - backend


  spiderfoot:
    container_name: spiderfoot
    image: spiderfoot:latest
    build: https://github.com/smicallef/spiderfoot.git
    networks:
      - backend
  
  spiderfoot-api:
    container_name: spiderfoot-api
    build:
      context: ./spiderfoot-api
      dockerfile: Dockerfile
    image: spiderfoot-api:latest
    networks:
      - backend
    ports:
      - "8001:8001" # remove in prod
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication_db
      POSTGRES_HOST: postgres

  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_GATEWAY_URL=http://api-gateway:8080
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - api-gateway

networks:
  backend:
    driver: bridge

volumes:
  maildata:
  mailstate:
  maillogs:
  webmail_data:
  gophish-data: