server:
  log_level: info
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  # 'ring' no longer sits directly under 'ingester'; it is under 'lifecycler'.
  lifecycler:
    join_after: 0s
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1536000
  max_transfer_retries: 0

querier:
  # Remove query_store_after and store_gateway_addresses (no longer valid here).
  engine:
    max_look_back_period: 0s

query_range:
  # Remove any deprecated fields like 'query_store_after'.
  cache_results: false
  parallelise_shardable_queries: false
  split_queries_by_interval: 0

# Usually needed to auto-create new tables/index if using local FS.
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    shared_store: filesystem
    cache_location: /tmp/loki/boltdb-shipper-cache
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 8
  max_concurrent_tail_requests: 20