name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for advanced build features.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Validate Docker Compose configuration.
      - name: Validate Docker Compose configuration
        run: docker-compose -f docker-compose.yml config

      # Step 4: Build the authentication-service image.
      - name: Build authentication-service Image
        run: |
          docker build \
            --file authentication/Dockerfile \
            --tag authentication-service:latest \
            authentication

      # Step 5: Build the api-gateway image.
      - name: Build api-gateway Image
        run: |
          docker build \
            --file gateway/Dockerfile \
            --tag api-gateway:latest \
            gateway

      # Step 6: Build the formation-service image.
      - name: Build formation-service Image
        run: |
          docker build \
            --file formation/Dockerfile \
            --tag formation-service:latest \
            formation

      # Step 7: Build the scoring-service image.
      - name: Build scoring-service Image
        run: |
          docker build \
            --file scoring/Dockerfile \
            --tag scoring-service:latest \
            scoring

      # Step 8: Build the spiderfoot-api image.
      - name: Build spiderfoot-api Image
        run: |
          docker build \
            --file spiderfoot-api/Dockerfile \
            --tag spiderfoot-api:latest \
            spiderfoot-api

      # Step 9: Build the frontend image.
      - name: Build frontend Image
        run: |
          docker build \
            --file frontend/Dockerfile \
            --tag frontend:latest \
            frontend
